# Generated by Django 5.2.4 on 2026-08-17 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_assignment_evaluationtemplate_individualevaluation_and_more'),
        ('teams', '0004_alter_teammember_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamUserScoreSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_seed', models.FloatField(default=0.0, verbose_name='누적 시드 점수')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_seeds', to='evaluations.evaluationround')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_seeds', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_seeds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
