# Generated by Django 5.2.4 on 2026-08-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_assignment_evaluationtemplate_individualevaluation_and_more'),
        ('teams', '0005_teamuserscoreseed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamuserscoreseed',
            options={'verbose_name': '팀 사용자 누적 시드', 'verbose_name_plural': '팀 사용자 누적 시드 목록'},
        ),
        migrations.AlterField(
            model_name='teamuserscoreseed',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_seeds', to='evaluations.evaluationround', verbose_name='소속 평가 회차'),
        ),
        migrations.AlterField(
            model_name='teamuserscoreseed',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_seeds', to='teams.team', verbose_name='소속 팀'),
        ),
        migrations.AlterField(
            model_name='teamuserscoreseed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_seeds', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddConstraint(
            model_name='teamuserscoreseed',
            constraint=models.UniqueConstraint(fields=('user', 'round'), name='uq_user_round_seed_once'),
        ),
        migrations.AlterModelTable(
            name='teamuserscoreseed',
            table='TEAM_USER_SCORE_SEED',
        ),
    ]
