# Generated by Django 5.2.4 on 2026-08-18 03:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_/Korean only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='한글, 영문, 숫자 및 특수문자(.@+-)만 사용할 수 있습니다.', regex='^[\\w가-힣.@+-]+$')]),
        ),
    ]
