# Generated by Django 5.2.4 on 2026-08-16 17:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_evaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationround',
            name='title',
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='회차 종료 일시'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='individual_rank_visible',
            field=models.BooleanField(default=False, verbose_name='개인 전체 석차 공개 여부'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='individual_score_visible',
            field=models.BooleanField(default=False, verbose_name='개인 점수 공개 여부'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='individual_weight',
            field=models.FloatField(default=0.6, verbose_name='개인 성적 비율'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='name',
            field=models.CharField(default='테스트 회차', max_length=100, verbose_name='평가 회차 이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='회차 시작 일시'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='student_weight',
            field=models.FloatField(default=0.5, verbose_name='학생 평가 비율'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='team_first_rank_visible',
            field=models.BooleanField(default=False, verbose_name='팀 1위 공개 여부'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='team_rank_visible',
            field=models.BooleanField(default=False, verbose_name='전체 팀 순위 공개 여부'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='team_weight',
            field=models.FloatField(default=0.4, verbose_name='팀 성적 비율'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='tutor_weight',
            field=models.FloatField(default=0.5, verbose_name='튜터 평가 비율'),
        ),
        migrations.AddField(
            model_name='evaluationround',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evaluationround',
            name='status',
            field=models.CharField(choices=[('draft', '작성 중'), ('ready', '대기'), ('in_progress', '진행 중'), ('finished', '종료')], default='draft', max_length=30, verbose_name='회차 전체 상태'),
        ),
    ]
