# Generated by Django 5.2.4 on 2026-08-17 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_alter_evaluation_evaluator_alter_evaluation_target'),
        ('teams', '0004_alter_teammember_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='과제 제목')),
                ('description', models.TextField(blank=True, verbose_name='과제 설명')),
                ('eval_start_at', models.DateTimeField(blank=True, null=True, verbose_name='평가 시작 일시')),
                ('eval_end_at', models.DateTimeField(blank=True, null=True, verbose_name='평가 종료 일시')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='evaluations.evaluationround')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEAM', '팀 평가'), ('INDIVIDUAL', '개인 평가'), ('TUTOR', '튜터 평가')], max_length=20, verbose_name='템플릿 유형')),
                ('criteria', models.JSONField(default=dict, verbose_name='문항 목록 (JSON)')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='evaluations.evaluationround')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='계산 점수')),
                ('responses', models.JSONField(default=dict, verbose_name='문항별 점수 및 서술 의견')),
                ('is_final', models.BooleanField(default=False, verbose_name='최종 제출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_individual_evaluations', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_evaluations', to='evaluations.evaluationround')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_individual_evaluations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_evaluations', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.FloatField(verbose_name='최종 팀 평가점수')),
                ('individual_score', models.FloatField(verbose_name='최종 개인 평가점수')),
                ('final_score', models.FloatField(verbose_name='최종 합산점수')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='석차')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to='evaluations.evaluationround')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='계산 점수')),
                ('responses', models.JSONField(default=dict, verbose_name='문항별 점수 및 서술 의견')),
                ('is_final', models.BooleanField(default=False, verbose_name='최종 제출 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_team_evaluations', to='teams.team')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_evaluations', to='evaluations.evaluationround')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_team_evaluations', to=settings.AUTH_USER_MODEL)),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_team_evaluations', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TutorEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='계산 점수')),
                ('responses', models.JSONField(default=dict, verbose_name='문항별 점수 및 서술 의견')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_tutor_evaluations', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_evaluations', to='evaluations.evaluationround')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_evaluations_as_target', to='teams.team', verbose_name='팀 평가 대상')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_evaluations_as_target', to=settings.AUTH_USER_MODEL, verbose_name='개인 평가 대상자')),
            ],
        ),
    ]
