# Generated by Django 5.2.4 on 2026-08-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_alter_evaluation_round_alter_evaluation_score_and_more'),
        ('evaluations', '0007_split_tutor_template_type'),
    ]

    operations = [
    ]
