# Generated by Django 5.2.4 on 2026-08-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_alter_evaluation_evaluator_alter_evaluation_target'),
        ('students', '0002_student_user'),
        ('teams', '0004_alter_teammember_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
